config/routes.rb
Rails.application.routes.draw do
  resources :tikas, except: [:new]
  get '/index', to: 'content_pages#index'
  get '/latest', to: 'content_pages#latest'
  get '/quotes/export'
  post '/quotes/import'
  resources :quotes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/resume', to: 'static_pages#resume'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/resources/export'
  post '/resources/import'
  resources :resources, except: [:new]
  get '/posts/export'
  post '/posts/import'
  resources :posts
  resources :comments, only: [:create, :update, :destroy]
end

app/controllers/content_pages_controller.rb
class ContentPagesController < ApplicationController
  def index
    @resources = correct_content(Resource).all
    @quotes = correct_content(Quote).all
    @posts = correct_content(Post).all
  end

  def latest
    @resource = correct_content(Resource).first
    @quote = correct_content(Quote).first
    @post = correct_content(Post).first
  end

  private

  def correct_content(active_record)
    logged_in? ? active_record.all.with_tags : active_record.only_public.with_tags
  end
end

app/helpers/content_pages_helper.rb
module ContentPagesHelper
end

app/views/content_pages/index.html.erb
<% provide(:title, 'All contents') %>

<main class="w-full max-w-5xl px-8 pb-8 mx-auto mt-16 text-left">

  <h1> All contents </h1>
  <a href="#posts" data-turbolinks="false"> Posts</a>
  <a href="#quotes" data-turbolinks="false"> Quotes</a>
  <a href="#resources" data-turbolinks="false"> Resources</a>

  <section id="posts" class="pt-8">
    <h2 class="w-full my-6 text-2xl leading-none"> Posts </h2>
    <ul style="columns: auto 18rem; column-gap: 6rem; column-rule: solid 1px lightgray;">
      <% @posts.each do |post| %>
        <li style="break-inside: avoid">

          <article class="pb-6 mb-8 text-left border-b border-gray-400 ">
            <%= link_to post.title, post_path(post), title: post_path(post),
                        class: "text-2xl mr-auto leading-tight inline-block mt-auto
                  text-default no-underline hover:underline" %>
            <span class="block my-2 text-xs">
              <%= time_tag(post.created_at, format: "%B %d, %Y") %> -
              <%= "#{((post.body.to_s.split.count)./ 170.0).ceil} minutes read" %>
            </span>
            <%= render "shared/tag_list", content: post %>
          </article>

        </li>
      <% end %>
    </ul>
  </section>

  <section id="resources" class="pt-8">
    <h2 class="w-full my-6 text-2xl leading-none "> Resources </h2>
    <ul style="columns: auto 18rem; column-gap: 6rem; column-rule: solid 1px lightgray;">
      <% @resources.each do |resource| %>
          <li style="break-inside: avoid">

            <article class="pb-6 mb-8 border-b border-gray-400">
              <%= link_to resource.title, resource.link, title: resource.link,
                          target: '_blank', rel:'noreferrer',
                          class: "text-2xl mr-auto leading-tight inline-block mt-auto" %>
              <cite class="block my-2 font-bold leading-none"> &#8213; <%= resource.author %>
                <% unless resource.publication.nil? %>
                  on <%= time_tag(resource.publication) %>
                <% end %>
              </cite>
              <%= render "shared/tag_list", content: resource %>
            </article>

          </li>
        <% end %>
    </ul>
  </section>

  <section id="quotes" class="pt-8">
    <h2 class="w-full my-6 text-2xl leading-none"> Quotes </h2>
    <ul style="columns: auto 18rem; column-gap: 6rem; column-rule: solid 1px lightgray;">
      <% @quotes.each do |quote| %>
        <li style="break-inside: avoid">

          <article class="pb-6 mb-8 border-b border-gray-400">
            <blockquote class="my-3">
              <p class="font-serif text-lg leading-tight">
                “<%= raw quote.body %>”
              </p>
              <footer class="mt-3 font-bold leading-none">
                &#8213; <%= quote.author %>, in <cite> <%= quote.source %></cite>
              </footer>
            </blockquote>
            <%= render "shared/tag_list", content: quote %>
          </article>

        </li>
      <% end %>
    </ul>
    </section>


</main>

app/views/content_pages/latest.html.erb
<% provide(:title, 'Latest contents') %>

<main class="w-full max-w-5xl px-8 pb-8 mx-auto mt-16 text-left">

  <h1> Latest contents </h1>

  <h2 class="pt-12 inline-block leading-none">
    <%= link_to 'Latest post', post_path(@post),
                class: "no-underline text-default-soft hover:underline text-xl" %></h2>
  <span class="text-sm mx-2 mt-auto leading-none">
    <%= link_to 'All posts', posts_path %></span>

  <%= render @post %>

  <h2 class="pt-12 inline-block leading-none">
    <%= link_to 'Latest quote', quote_path(@quote),
                class: "no-underline text-default-soft hover:underline text-xl" %></h2>
  <span class="text-sm mx-2 mt-auto leading-none">
    <%= link_to 'All quotes', quotes_path %></span>

  <%= render @quote %>

  <h2 class="pt-12 inline-block leading-none">
    <%= link_to 'Latest resource', resource_path(@resource),
                class: "no-underline text-default-soft hover:underline text-xl" %></h2>
  <span class="text-sm mx-2 mt-auto leading-none">
    <%= link_to 'All resources', resources_path %></span>


  <%= render @resource %>

</main>