config/routes.rb
Rails.application.routes.draw do
  resources :tikas, except: [:new]
  get '/index', to: 'content_pages#index'
  get '/latest', to: 'content_pages#latest'
  get '/quotes/export'
  post '/quotes/import'
  resources :quotes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/resume', to: 'static_pages#resume'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/resources/export'
  post '/resources/import'
  resources :resources, except: [:new]
  get '/posts/export'
  post '/posts/import'
  resources :posts
  resources :comments, only: [:create, :update, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="bottom-0 z-10 p-4 text-center bg-gray-800">
  <h3 class="my-0 font-semibold leading-loose text-gray-300">Contact Info</h3>

  <a class="my-0 font-semibold leading-loose text-gray-300"
     href="mailto:ulysse.brisson@gmail.com">
    ulysse.brisson@gmail.com
  </a>

  <a class="my-0 font-semibold leading-loose text-gray-300"
     href="https://github.com/ubrisson"
     target="_blank" rel="noreferrer">
    Github
  </a>

  <a class="my-0 font-semibold leading-loose text-gray-300"
     href="https://www.linkedin.com/in/ulysse-brisson/"
     target="_blank" rel="noreferrer">
    Linkedin
  </a>
</footer>

app/views/layouts/_header.html.erb
<div id="placeholder" class="lg:min-w-1/8 lg:inset-y-0"></div>
<header class="top-0 z-10 left-0 flex flex-col justify-center w-full text-left bg-inverse lg:fixed lg:min-w-1/8 lg:w-auto lg:inset-y-0">
  <nav>
    <ul class="flex flex-row flex-wrap justify-between px-6 lg:flex-col">
      <li class="py-2 px-1 list-none">
        <%= link_to "Home", root_path,
                    class: "hover-underline-animation text-inverse font-semibold no-underline py-3 lg:py-2 leading-none" %>
      </li>

      <li class="py-2 px-1 list-none">
        <%= link_to "Latest", latest_path,
                    class: "hover-underline-animation text-inverse font-semibold no-underline py-3 lg:py-2 leading-none" %>
      </li>

      <li class="py-2 px-1 list-none">
        <%= link_to "Posts", posts_path,
                    class: "hover-underline-animation text-inverse font-semibold no-underline py-3 lg:py-2 leading-none" %>
      </li>

      <li class="py-2 px-1 list-none">
        <%= link_to "Quotes", quotes_path,
                    class: "hover-underline-animation text-inverse font-semibold no-underline py-3 lg:py-2 leading-none" %>
      </li>

      <li class="py-2 px-1 list-none">
        <%= link_to "Resources", resources_path,
                    class: "hover-underline-animation text-inverse font-semibold no-underline py-3 lg:py-2 leading-none" %>
      </li>

      <li class="py-2 px-1 list-none">
        <%= link_to "Resume", resume_path,
                    class: "hover-underline-animation text-inverse font-semibold no-underline py-3 lg:py-2 leading-none" %>
      </li>

      <li class="py-2 px-1 list-none">
        <%= link_to "Index", index_path,
                    class: "hover-underline-animation text-inverse font-semibold no-underline py-3 lg:py-2 leading-none" %>
      </li>

      <li class="fixed bottom-0 lg:top-0 right-0 list-none flex flex-col text-center ">
        <% if logged_in? %>

          <%= link_to "Log out", logout_path, method: :delete,
                      class: "text-primary opacity-50 no-underline bg-secondary
                    pl-4 pr-3 pt-2 pb-3 font-semibold hover:opacity-100 hover:underline" %>

          <%= link_to "TIKAs", tikas_path,
                      class: "text-primary opacity-50 no-underline bg-secondary rounded-bl-lg
                    pl-4 pr-3 pt-2 pb-3 font-semibold hover:opacity-100 hover:underline" %>
        <% else %>
          <%= link_to "Private access", login_path,
                      class: "text-transparent no-underline hover:bg-inverse rounded-bl-lg
                    pl-4 pr-3 pt-2 pb-3 hover:text-inverse font-semibold" %>
        <% end %>
      </li>
    </ul>
  </nav>
  <button id="ThemeSwitchBtn"
          class="lg:mt-4 text-primary text-sm uppercase tracking-wide
          font-bold  bg-default border p-2
          border-transparent cursor-default z-20
          hover:bg-secondary hover:border-secondary"
  > Switch Theme </button>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" style="font-family: Arial, sans-serif" id="html"
      class="h-full text-base text-center text-default bg-default 2xl:text-xl nymous:text-4xl
      <%= request.cookies["lightTheme?"] == 'false' ? 'theme-dark' : 'theme-light' %>" >
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="description" content="The personal website - blog - journal of someone.
   Running on Ruby on Rails and TailwindCSS">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_pack_tag 'application', defer: true,'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application','data-turbolinks-track': 'reload' %>
  <%= yield :script %>
</head>

<% if yield(:title).blank? %>
  <%= yield %>
<% else %>
  <body>

  <div class="flex flex-col justify-around max-w-full pb-6 mx-auto lg:flex-row">
  <%= render 'layouts/header' %>

  <% flash.each do |message_type, message| %>
    <% case message_type
       when 'danger' then
         color = 'red'
       when 'success' then
         color = 'green'
       else
         color = 'yellow'
       end %>

    <!--  css classes for purgecss -->
    <!--  bg-red-100 text-red-600 border-red-300 -->
    <!--  bg-green-100 text-green-600 border-green-300 -->
    <!--  bg-yellow-100 text-yellow-600 border-yellow-300 -->

    <%= content_tag :div, message,
                    class: "absolute max-w-xs mx-auto border rounded-lg
                  p-2 inset-x-0 top-0 mt-16 md:mt-4
                  bg-#{color}-100 text-#{color}-600 border-#{color}-300
                  " %>
  <% end %>

  <%= yield %>

  </div>
  <%= render 'layouts/footer' %>
  </body>
<% end %>

</html>